name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup pnpm 11
        run: |
          corepack enable
          corepack prepare pnpm@latest-11 --activate

      - name: Cache pnpm files
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      # Build shared packages FIRST
      - name: Build UI Packages
        run: pnpm --filter @flightlesslabs/* build

      # Build homepage
      - name: Build Homepage
        run: pnpm --filter @documentation/homepage build

      # Build Storybook
      - name: Build Storybook
        run: pnpm --filter @documentation/docs build

      # Merge outputs
      - name: Merge Storybook into Homepage
        run: |
          mkdir -p deploy

          # Copy homepage
          cp -r documentation/homepage/dist/* deploy/

          # Create docs folder
          mkdir -p deploy/docs

          # Copy storybook
          cp -r documentation/docs/storybook-static/* deploy/docs/

      # Prevent Jekyll processing
      - name: Add .nojekyll
        run: touch deploy/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: deploy
